version: '3.3'

services:
  fireflyiii-dev:
    image: fireflyiii/core:develop
    volumes:
      - firefly_iii_upload_dev:/var/www/html/storage/upload
    env_file: .firefly-env
    ports:
      - 8081:8080
    depends_on:
      - fireflyiiidb-dev
    restart: unless-stopped
  
  fireflyiiidb-dev:
    image: postgres:10-alpine
    env_file: .db-env
    volumes:
      - firefly_iii_db_dev:/var/lib/postgresql/data
    restart: unless-stopped
  
  # uncomment below to use
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   ports:
  #     - 3000:80
  #   env_file: .pgadmin-env

  watchtower:
    image: containrrr/watchtower:amd64-1.1.6
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    # check for new images every Monday at 9:00 UTC and only watch watchtower,
    # and fireflyiii develop container where the tag of the image is "develop".
    # remove old images after updating watched containers
    # this compose file will have the one watchtower image to control all of the various
    # related firefly containers
    command: watchtower firefly-iii-dev --schedule "0 9 * * 1" --cleanup
    # provide slack web hook url to get notifications when the containers update
    env_file: .watchtower-env
    restart: unless-stopped # restarts container unless we explicitly stop it

volumes:
   firefly_iii_upload_dev:
   firefly_iii_db_dev: